### Registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "username",
    "password": "password",
    "validation": ""
}

### récupération des lists
GET http://localhost:3000/lists

### création de liste
POST http://localhost:3000/lists
Content-Type: application/json

{
    "id": 3
}