### Registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "username",
    "password": "password",
    "validation": "password"
}

### Login
## token admin : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NjA1MTI1NjgsImV4cCI6MTc2MDUyNjk2OH0.hnqN57LjbjD2HOUrKLYoGXnY1V3beTQp42f3BPm376E
## token user : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NjA1MzY3NTYsImV4cCI6MTc2MDU1MTE1Nn0.hQkaowOkgXHQW0v2mIs9P3RqnHJFQCf20X9HzaYav4k
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "username",
    "password": "password"
}

### récupération des lists
## pour envoyer un token dans une requete HTTP, on ajoute un header
## avec pour clef ̀ Authorization` 
## et comme valeur `Bearer ` suivi du token
GET http://localhost:3000/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NjA1MzY3NTYsImV4cCI6MTc2MDU1MTE1Nn0.hQkaowOkgXHQW0v2mIs9P3RqnHJFQCf20X9HzaYav4k

### LIST ADMIN
GET http://localhost:3000/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NjA1MTI1NjgsImV4cCI6MTc2MDUyNjk2OH0.hnqN57LjbjD2HOUrKLYoGXnY1V3beTQp42f3BPm376E

### création de liste
POST http://localhost:3000/lists
Content-Type: application/json

{
    "id": 3
}

### auth/me
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NjA1MTI1NjgsImV4cCI6MTc2MDUyNjk2OH0.hnqN57LjbjD2HOUrKLYoGXnY1V3beTQp42f3BPm376E



### création de liste
POST http://localhost:3000/lists
Content-Type: application/json

{
    "id": 3
}

### route /users limitée aux admins uniquement
GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NjA1MzY3NTYsImV4cCI6MTc2MDU1MTE1Nn0.hQkaowOkgXHQW0v2mIs9P3RqnHJFQCf20X9HzaYav4k

### Mistral prompt
POST http://localhost:3000/prompt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiaWF0IjoxNzYwNjAyMjU4LCJleHAiOjE3NjA2MTY2NTh9.zvW4kW4pAeCtDGczpzOroubD_mxO70i9lylAWAWLs9I

{
    "prompt": "En une phrase, quelle est la couleur du ciel ?"
}