### Registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "username",
    "password": "password",
    "validation": "password"
}

### Login
## token admin : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NjA1MTI1NjgsImV4cCI6MTc2MDUyNjk2OH0.hnqN57LjbjD2HOUrKLYoGXnY1V3beTQp42f3BPm376E
## token user : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NjA0NDU1OTEsImV4cCI6MTc2MDQ1OTk5MX0.6z3Fhc23io0Pa86TMtHrUxA_NLbyMDI9DVUilckdgf0
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### récupération des lists
## pour envoyer un token dans une requete HTTP, on ajoute un header
## avec pour clef ̀ Authorization` 
## et comme valeur `Bearer ` suivi du token
GET http://localhost:3000/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NjA1MTI1NjgsImV4cCI6MTc2MDUyNjk2OH0.hnqN57LjbjD2HOUrKLYoGXnY1V3beTQp42f3BPm376E

### création de liste
POST http://localhost:3000/lists
Content-Type: application/json

{
    "id": 3
}

### auth/me
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NjA1MTI1NjgsImV4cCI6MTc2MDUyNjk2OH0.hnqN57LjbjD2HOUrKLYoGXnY1V3beTQp42f3BPm376E
